# Generated by Django 3.0.5 on 2020-04-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CallList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contactView',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactName',
            field=models.CharField(default='', max_length=300),
        ),
    ]
