# Generated by Django 3.0.5 on 2020-04-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CallList', '0002_auto_20200411_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contactName',
            field=models.CharField(default='', max_length=300, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactView',
            field=models.CharField(default='', max_length=300, verbose_name='Представление'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='use',
            field=models.BooleanField(default=False, verbose_name='Использовать'),
        ),
        migrations.AlterField(
            model_name='skypeauth',
            name='login',
            field=models.CharField(max_length=200, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='skypeauth',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Пароль'),
        ),
    ]
