# Generated by Django 3.0.5 on 2020-04-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CallList', '0005_skypeauth1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkypeAuth1',
        ),
    ]
